from humanise.prompts.templates import (
    ANTI_DETECTION_PROMPT,
    FEEDBACK_PROMPT,
    SCRAMBLE_PROMPT,
    PASS_1_STRUCTURAL,
    PASS_2_VOCABULARY,
    PASS_3_PUNCTUATION,
    PASS_4_FINGERPRINT,
    FEEDBACK_MULTI_PASS,
)

__all__ = [
    "ANTI_DETECTION_PROMPT",
    "FEEDBACK_PROMPT",
    "SCRAMBLE_PROMPT",
    "PASS_1_STRUCTURAL",
    "PASS_2_VOCABULARY",
    "PASS_3_PUNCTUATION",
    "PASS_4_FINGERPRINT",
    "FEEDBACK_MULTI_PASS",
]
