ANTI_DETECTION_PROMPT = """Rewrite the following text to read like a skilled human writer wrote it. The original was generated by AI and will be flagged by detectors. Your rewrite must pass as human.

WHAT DETECTORS CATCH — avoid these or the text WILL fail:

1. PREDICTABLE PATTERNS:
   - "eyes sparkled/narrowed/flashed/lit up", "smile faltered", "heart pounded/raced", "chest tightened", "gut twisted", "drowning in her eyes", "surge of sympathy", "voice barely above a whisper"
   - BANNED phrases: "melodious voice", "captivated by", "filled the air", "beacon of hope", "symbol of resilience", "tapestry of", "dance of chaos"
   - Replace physical-emotion cliches with specific, unusual observations or just skip them.

2. RHYTHM:
   - AI text has sentences of uniform length (12-18 words each). Break this. Write some sentences that are 3-5 words. Some that are 25-35. Not all fragments — real variety.
   - Don't start consecutive sentences with the same word. Don't start 3+ paragraphs with the same structure.
   - Use normal sentence structure. Fragments are fine occasionally, not constantly.

3. DIALOGUE:
   - Don't attach emotional descriptions to every line of dialogue. Sometimes just "she said."
   - Banned: "she said, her voice [trembling/breaking/barely above a whisper/filled with]"
   - Let the words themselves carry the emotion. Trust the reader.

4. NARRATIVE TRANSITIONS:
   - Avoid: "As they walked/talked/worked...", "For a moment...", "Suddenly...", "Little did he know..."
   - Jump cuts are fine. Real writers don't explain every transition.

5. WORD CHOICE:
   - No decoration words. If an adjective doesn't carry real information, cut it.
   - Skip all sigma adjectives: innovative, groundbreaking, cutting-edge, comprehensive, etc.
   - Use plain, strong words. "The onions smelled good" beats "the aroma of sizzling onions wafted through the air."

6. AUTHENTIC FEEL:
   - Include one small, weird detail per paragraph that an AI wouldn't think to mention — a broken tile, a faded sticker, a specific brand name, an ugly color.
   - The writing should feel like it was typed by a person with opinions, not generated by a model with probabilities.
   - Some sentences can be blunt. Some beautiful. The mix is what makes it human.

IMPORTANT: The output must be enjoyable to read. Natural prose. Vary sentence length but keep the writing flowing. Don't write in sentence fragments — write like a real author writes.

Rewrite the text below. Return NOTHING except the rewritten text."""


SELF_CHECK_PROMPT = """Analyze this text for AI detection risk. Check for:
- Sentence length uniformity (low variance = high AI signal)
- Predictable word sequences (low perplexity = high AI signal)  
- Stock emotional descriptions ("eyes sparkled", "heart raced", etc.)
- Formulaic dialogue attribution ("she said, her voice barely above a whisper")
- Transitional cliches ("As they walked...", "For a moment...", "Suddenly...")
- Paragraph structure uniformity

TEXT: '''{text}'''

Return a JSON object with:
- detection_risk: 0-100 (0 = human-passing, 100 = certain AI flag)
- burstiness: 0-2 (under 0.4 is high risk)
- predictability_issues: list of specific problems
- flagged_phrases: phrases most likely to trigger detectors
- rewrite_needed: list of sentences that must be rewritten

Return ONLY valid JSON. No markdown."""


TONE_PROFILES = {
    "casual": (
        "Write in a relaxed, conversational tone. Use contractions where natural, "
        "sentence fragments where they serve rhythm, and a friendly voice. Write like "
        "you're explaining something to a colleague over coffee — not performing casualness."
    ),
    "academic": (
        "Write in a scholarly but still human voice. Use varied sentence structures, "
        "avoid formulaic transitions, include hedged claims where appropriate, "
        "and maintain intellectual rigor without sounding like an LLM. Real "
        "academics don't write 'furthermore, it is imperative to note that...'"
    ),
    "professional": (
        "Write like a knowledgeable professional who knows their field well enough "
        "to explain it clearly without jargon-crunching. Be authoritative but not "
        "robotic. Real experts use plain language when it works and technical terms "
        "when they're needed, not as decoration."
    ),
    "creative": (
        "Write with personality and flair. Use metaphors, vivid imagery, unexpected "
        "word choices, and a distinct voice. Take risks with structure. Creative "
        "writing should feel alive, not like a model filling in probability gaps."
    ),
    "technical": (
        "Write technical content that reads like an experienced engineer wrote it — "
        "precise where it matters, casual where it doesn't. Use 'we' for the "
        "reader and writer. Skip the academic hedging. Code talk should feel like "
        "a senior dev whiteboarding, not a textbook."
    ),
}
